latlong:
  ip2location:
    format: hex_tsv
    region_col: 3
    city_col: 4
    lat_col: 5
    long_col: 6
    ipv4: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/ip2location-city/ipv4.tsv?inline=false"
    ipv6: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/ip2location-city/ipv6.tsv?inline=false"
  geolite2:
    format: hex_tsv
    region_col: 3
    city_col: 5
    lat_col: 6
    long_col: 7
    ipv4: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/geolite2-city/ipv4-en.tsv?inline=false"
    ipv6: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/geolite2-city/ipv6-en.tsv?inline=false"
  dbip:
    format: hex_tsv
    region_col: 3
    city_col: 4
    lat_col: 5
    long_col: 6
    ipv4: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/dbip-city/ipv4.tsv?inline=false"
    ipv6: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/dbip-city/ipv6.tsv?inline=false"

country:
  geo-whois-asn-country:
    format: hex_tsv
    ipv4: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/geo-whois-asn-country/ipv4.tsv?inline=false"
    ipv6: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/geo-whois-asn-country/ipv6.tsv?inline=false"
  ipinfo-country:
    format: hex_tsv
    ipv4: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/ipinfo-country/ipv4.tsv?inline=false"
    ipv6: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/ipinfo-country/ipv6.tsv?inline=false"
  iplocate-country:
    # single combined (ipv4+ipv6) CIDR csv
    format: cidr_csv
    ipv4: "https://media.githubusercontent.com/media/iplocate/ip-address-databases/refs/heads/main/ip-to-country/ip-to-country.csv.zip"
    ipv6: "https://media.githubusercontent.com/media/iplocate/ip-address-databases/refs/heads/main/ip-to-country/ip-to-country.csv.zip"
